name: 'Continuous Integration'
on:
  push:
    branches-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-docker-images:
    # run this job if the unit tests passed and the npm-publish job was a success or was skipped
    # note: github actions won't run a job if you don't call one of the status check functions, so `always()` is called since it evalutes to `true`
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker images
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl "https://raw.githubusercontent.com/pelias/ci-tools/master/build-docker-images.sh" | bash -
